outroTesteVs/force-app/main/default/objects/Aluno__c/Aluno__c.object-meta.xml
<CustomObject>
    <label>Aluno</label>
    <nameField>
        <displayFormat>Alu-{000000}</displayFormat>
        <label>Cósigo do Aluno</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alunos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Aluno__c/fields/Pessoa__c.field-meta.xml
<CustomField>
    <fullName>Pessoa__c</fullName>
    <label>Pessoa</label>
    <referenceTo>Pessoa__c</referenceTo>
    <relationshipLabel>Alunos</relationshipLabel>
    <relationshipName>Alunos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Disciplina__c/Disciplina__c.object-meta.xml
<CustomObject>
    <label>Disciplina</label>
    <nameField>
        <label>Nome de Disciplina</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disciplinas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Disciplina__c/fields/Professor__c.field-meta.xml
<CustomField>
    <fullName>Professor__c</fullName>
    <label>Professor</label>
    <referenceTo>Professor__c</referenceTo>
    <relationshipLabel>Disciplinas</relationshipLabel>
    <relationshipName>Disciplinas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Notas__c/Notas__c.object-meta.xml
<CustomObject>
    <label>Nota</label>
    <nameField>
        <displayFormat>Nota-{000000}</displayFormat>
        <label>Cod de Notas</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Aluno__c.field-meta.xml
<CustomField>
    <fullName>Aluno__c</fullName>
    <label>Aluno</label>
    <referenceTo>Aluno__c</referenceTo>
    <relationshipLabel>Notas</relationshipLabel>
    <relationshipName>Notas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Disciplina__c.field-meta.xml
<CustomField>
    <fullName>Disciplina__c</fullName>
    <label>Disciplina</label>
    <referenceTo>Disciplina__c</referenceTo>
    <relationshipLabel>Notas</relationshipLabel>
    <relationshipName>Notas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Resultado__c.field-meta.xml
<CustomField>
    <fullName>Resultado__c</fullName>
    <label>Resultado</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Turma__c.field-meta.xml
<CustomField>
    <fullName>Turma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Notas</relationshipLabel>
    <relationshipName>Notas</relationshipName>
    <type>Lookup</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Valor_Total__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total__c</fullName>
    <label>Valor Total</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Pessoa__c/Pessoa__c.object-meta.xml
<CustomObject>
    <label>Pessoa</label>
    <nameField>
        <label>Nome de Pessoa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pessoas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Pessoa__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Professor__c/Professor__c.object-meta.xml
<CustomObject>
    <label>Professor</label>
    <nameField>
        <displayFormat>Pro-{000000}</displayFormat>
        <label>Código do Professor</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Professores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Professor__c/fields/Pessoa__c.field-meta.xml
<CustomField>
    <fullName>Pessoa__c</fullName>
    <label>Pessoa</label>
    <referenceTo>Pessoa__c</referenceTo>
    <relationshipLabel>Professores</relationshipLabel>
    <relationshipName>Professores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Sala__c/Sala__c.object-meta.xml
<CustomObject>
    <label>Sala</label>
    <nameField>
        <label>Código Sala</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Sala__c/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <label>Endereço</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Turma__c/Turma__c.object-meta.xml
<CustomObject>
    <label>Turma</label>
    <nameField>
        <displayFormat>Tur-{00000}</displayFormat>
        <label>Código Turma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Turmas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Turma__c/fields/Ano__c.field-meta.xml
<CustomField>
    <fullName>Ano__c</fullName>
    <label>Ano</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Turma__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa</label>
    <type>Checkbox</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Turma__c/fields/Curso__c.field-meta.xml
<CustomField>
    <fullName>Curso__c</fullName>
    <label>Curso</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Turma__c/fields/Periodo__c.field-meta.xml
<CustomField>
    <fullName>Periodo__c</fullName>
    <label>Periodo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manhã</fullName>
                <default>true</default>
                <label>Manhã</label>
            </value>
            <value>
                <fullName>Tarde</fullName>
            </value>
            <value>
                <fullName>Noite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

outroTesteVs/force-app/main/default/objects/Turma__c/fields/Sala__c.field-meta.xml
<CustomField>
    <fullName>Sala__c</fullName>
    <label>Sala</label>
    <referenceTo>Sala__c</referenceTo>
    <relationshipLabel>Turmas</relationshipLabel>
    <relationshipName>Turmas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

outroTesteVs/force-app/main/default/classes/TESTapiGetReportCard.cls
@isTest public class TESTapiGetReportCard {

    @testSetUp static void MeuSetup(){
        //SetUp  
        //Cria Pessoa

        //Teste DataBase
        //Savepoint sp = Database.setSavepoint();

        Pessoa__c p1 = new Pessoa__c(name = 'PessoaTeste',
                                     E_mail__c = 'teste20@teste.com', 
                                     Password__c = 'abc123');
        insert p1;

        Aluno__c a = new Aluno__c(Pessoa__c = p1.id);
        insert a;

        Pessoa__c p2 = new Pessoa__c(name = 'PessoaTeste2',
                                     E_mail__c = 'teste30@teste.com', 
                                     Password__c = 'abc123');
        insert p2;
        
        Professor__C pf = new Professor__C(Pessoa__c = p2.id);
        insert pf;


        Sala__c s = new Sala__c(Endereco__c = 'SALA30');
        insert s;

        Turma__c t = new Turma__c(Ano__c = 2021, 
                                  Ativa__c = True, 
                                  Curso__c = 'Nome do Curso', 
                                  Periodo__c = 'Manhã',
                                  Sala__c = s.id);
        insert t;
        
        Disciplina__c d = new Disciplina__c(Professor__C = pf.id,
                                            Name = 'Nome Disciplina');
        insert d;
        
        Notas__c n = new Notas__c(Aluno__c = a.id, 
                                  Descricao__c = 'Prova Teste 1', 
                                  Disciplina__c = d.id,
                                  Resultado__c = 8,
                                  Turma__c = t.id,
                                  Valor_Total__c = 10);
        insert n;
        
        //Database.rollback(sp);
    }

    @isTest public static void getStudentOK(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = 'https://teste-andremgbr-developer-edition.na213.force.com/services/apexrest/GetCardStudent';
        req.addParameter('email', 'teste30@teste.com');
        req.addParameter('password','abc123');
        req.addHeader('Content-Type', 'application/json');
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof('{}');

        RestContext.request  = req;
        RestContext.response = res;  

        Test.startTest();
        apiGetReportCard.GetCardStudent();
        Test.stopTest();

        System.AssertEquals(200,res.statusCode);
    }

    @isTest public static void getStudentNotFound(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = 'https://teste-andremgbr-developer-edition.na213.force.com/services/apexrest/GetCardStudent';
        req.addParameter('email', 'teste50@teste.com');
        req.addParameter('password','abc123');
        req.addHeader('Content-Type', 'application/json');
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof('{}');

        RestContext.request  = req;
        RestContext.response = res;  

        Test.startTest();
        apiGetReportCard.GetCardStudent();
        Test.stopTest();

        System.AssertEquals(404,res.statusCode);
    }

    @isTest public static void getStudentPassWordError(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = 'https://teste-andremgbr-developer-edition.na213.force.com/services/apexrest/GetCardStudent';
        req.addParameter('email', 'teste30@teste.com');
        req.addParameter('password','aaaa3');
        req.addHeader('Content-Type', 'application/json');
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof('{}');

        RestContext.request  = req;
        RestContext.response = res;  

        Test.startTest();
        apiGetReportCard.GetCardStudent();
        Test.stopTest();

        System.AssertEquals(401,res.statusCode);
    }
    @isTest public static void getStudentException(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = 'https://teste-andremgbr-developer-edition.na213.force.com/services/apexrest/GetCardStudent';
        req.addParameter('email', 'ERRO_DE_EXCEPTION_TESTE');
        req.addParameter('password','aaaa3');
        req.addHeader('Content-Type', 'application/json');
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof('{}');

        RestContext.request  = req;
        RestContext.response = res;  

        Test.startTest();
        apiGetReportCard.GetCardStudent();
        Test.stopTest();

        System.AssertEquals(500,res.statusCode);
    }
    

}