outroTesteVs/force-app/main/default/objects/Aluno__c/Aluno__c.object-meta.xml
<CustomObject>
    <label>Aluno</label>
    <nameField>
        <displayFormat>Alu-{000000}</displayFormat>
        <label>Cósigo do Aluno</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alunos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Aluno__c/fields/Pessoa__c.field-meta.xml
<CustomField>
    <fullName>Pessoa__c</fullName>
    <label>Pessoa</label>
    <referenceTo>Pessoa__c</referenceTo>
    <relationshipLabel>Alunos</relationshipLabel>
    <relationshipName>Alunos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Disciplina__c/Disciplina__c.object-meta.xml
<CustomObject>
    <label>Disciplina</label>
    <nameField>
        <label>Nome de Disciplina</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disciplinas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Notas__c/Notas__c.object-meta.xml
<CustomObject>
    <label>Nota</label>
    <nameField>
        <displayFormat>Nota-{000000}</displayFormat>
        <label>Cod de Notas</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Aluno__c.field-meta.xml
<CustomField>
    <fullName>Aluno__c</fullName>
    <label>Aluno</label>
    <referenceTo>Aluno__c</referenceTo>
    <relationshipLabel>Notas</relationshipLabel>
    <relationshipName>Notas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Disciplina__c.field-meta.xml
<CustomField>
    <fullName>Disciplina__c</fullName>
    <label>Disciplina</label>
    <referenceTo>Disciplina__c</referenceTo>
    <relationshipLabel>Notas</relationshipLabel>
    <relationshipName>Notas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Resultado__c.field-meta.xml
<CustomField>
    <fullName>Resultado__c</fullName>
    <label>Resultado</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Turma__c.field-meta.xml
<CustomField>
    <fullName>Turma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Notas</relationshipLabel>
    <relationshipName>Notas</relationshipName>
    <type>Lookup</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Notas__c/fields/Valor_Total__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total__c</fullName>
    <label>Valor Total</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Pessoa__c/Pessoa__c.object-meta.xml
<CustomObject>
    <label>Pessoa</label>
    <nameField>
        <label>Nome de Pessoa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pessoas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Turma__c/Turma__c.object-meta.xml
<CustomObject>
    <label>Turma</label>
    <nameField>
        <displayFormat>Tur-{00000}</displayFormat>
        <label>Código Turma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Turmas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

outroTesteVs/force-app/main/default/objects/Turma__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa</label>
    <type>Checkbox</type>
</CustomField>

outroTesteVs/force-app/main/default/objects/Turma__c/fields/Curso__c.field-meta.xml
<CustomField>
    <fullName>Curso__c</fullName>
    <label>Curso</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

outroTesteVs/force-app/main/default/classes/getReportCardStudent.cls
global class getReportCardStudent {

    global  class AllDataReport {
        
        @AuraEnabled
        public List<ReportLesson> ListRL;

        @AuraEnabled
        public string curso {get; set;}
    }

    public class ReportLesson {
        @AuraEnabled
        public string disciplina {get; set;}

        @AuraEnabled
        public string descricao {get; set;}

        @AuraEnabled
        public double notaTotal {get; set;}

        @AuraEnabled
        public double resultado {get; set;}
    }

    @AuraEnabled(cacheable=true)
    public  static AllDataReport ReportCard(String IdStudent){

        AllDataReport Data = new AllDataReport();
        
        List<Notas__c> notas = [select id, ALUNO__r.Pessoa__r.Name, DISCIPLINA__r.Name, 
                                        TURMA__r.Name, VALOR_TOTAL__C,
                                        RESULTADO__C, Descricao__c, TURMA__r.Curso__c
                                from Notas__c 
                                where Aluno__r.Pessoa__r.id = :IdStudent
                                and Turma__r.Ativa__c = TRUE];
        
        List<ReportLesson> ListReport = new List<ReportLesson>();

        for (Notas__c nota : notas){
            ReportLesson rl = new ReportLesson();
            rl.disciplina = nota.DISCIPLINA__r.Name;
            rl.notaTotal = nota.VALOR_TOTAL__C;
            rl.resultado = nota.RESULTADO__C;
            rl.descricao = nota.Descricao__c;
            ListReport.add(rl);
        }

        Data.ListRL = ListReport;
        Data.curso = notas.size() > 0 ? notas[0].TURMA__r.Curso__c : null;
        
        return Data;
    }

}